main: Clase.o DtClase.o DtEntrenamiento.o DtFecha.o DtSocio.o DtSpinning.o Entrenamiento.o Inscripciones.o Socio.o Spinning.o main.o
	g++ -o sistema Clase.o DtClase.o DtEntrenamiento.o DtFecha.o DtSocio.o DtSpinning.o Entrenamiento.o Inscripciones.o Socio.o Spinning.o main.o -g

Clase.o: Clase.cpp
	g++ -c Clase.cpp -g

DtClase.o: DtClase.cpp
	g++ -c DtClase.cpp -g

DtEntrenamiento.o: DtEntrenamiento.cpp
	g++ -c DtEntrenamiento.cpp -g

DtFecha.o: DtFecha.cpp 
	g++ -c DtFecha.cpp -g

DtSocio.o: DtSocio.cpp
	g++ -c DtSocio.cpp -g

DtSpinning.o: DtSpinning.cpp
	g++ -c DtSpinning.cpp -g

Entrenamiento.o: Entrenamiento.cpp
	g++ -c Entrenamiento.cpp -g

Inscripciones.o: Inscripciones.cpp
	g++ -c Inscripciones.cpp -g

Socio.o: Socio.cpp
	g++ -c Socio.cpp -g

Spinning.o: Spinning.cpp
	g++ -c Spinning.cpp -g

main.o: main.cpp
	g++ -c main.cpp -g

clean:
	rm -f *.o sistema
